### ISSUE TITLE
Fitur toimg eror

### ISSUE THREAD

**Issue by imamadi19** [rtwone/chitandabot#1]
![IMG_20211220_163842](https://user-images.githubusercontent.com/84767049/146746068-7e815041-7073-471f-b57b-9114f1cc75c7.jpg)

**Comment by rtwone** [comment]
> 

perasaan ga error dah, blum install ffmpeg kali

**Comment by imamadi19** [comment]
> > 
> 
> perasaan ga error dah, blum install ffmpeg kali

Udah install

**Comment by imamadi19** [comment]
> ![IMG_20211220_163842](https://user-images.githubusercontent.com/84767049/146746068-7e815041-7073-471f-b57b-9114f1cc75c7.jpg)

Nih banh

**Comment by imamadi19** [comment]
> > 
> 
> perasaan ga error dah, blum install ffmpeg kali

![IMG_20211220_164308](https://user-images.githubusercontent.com/84767049/146746682-c74f8e0d-1156-4bca-95d4-cdb97d55c08a.jpg)
Sama fitur tictactoe

**Comment by akmallxx** [comment]
> > > 
> > 
> > 
> > perasaan ga error dah, blum install ffmpeg kali
> 
> ![IMG_20211220_164308](https://user-images.githubusercontent.com/84767049/146746682-c74f8e0d-1156-4bca-95d4-cdb97d55c08a.jpg) Sama fitur tictactoe

ajg nama gw🗿

**Comment by akmallxx** [comment]
tambahin ini btw

```js
            case prefix+'giftbalance':
            case prefix+'gift':{
                 if (!isOwner) return reply(mess.OnlyOwner)
                 if (args.length < 2) return reply(`Kirim perintah *${command}* @tag nominal\nContoh : ${command} @6285791458996 2000`)
                 if (mentioned.length == 0) return reply(`Tag orang yang ingin di transfer balance`)
                 if (!args[2]) return reply(`Masukkan nominal nya!`)
                 if (isNaN(args[2])) return reply(`Nominal harus berupa angka!`)
                 if (args[2].toLowerCase() === 'infinity') return reply(`Yahaha saya ndak bisa di tipu`)
                 if (args[2].includes("-")) return reply(`Jangan menggunakan -`)
                 addBalance(mentioned[0], parseInt(args[2]), balance)
                 reply(`Sukses gift balance sebesar $${args[2]} kepada @${mentioned[0].split("@")[0]}`)
            }
            break
```

**Comment by imamadi19** [comment]
> tambahin ini btw
> 
> ```js
>             case prefix+'transfer':
>             case prefix+'tf':{
>                  if (args.length < 2) return reply(`Kirim perintah *${command}* @tag nominal\nContoh : ${command} @6285791458996 2000`)
>                  if (mentioned.length == 0) return reply(`Tag orang yang ingin di transfer balance`)
>                  if (!args[2]) return reply(`Masukkan nominal nya!`)
>                  if (isNaN(args[2])) return reply(`Nominal harus berupa angka!`)
>                  if (args[2].toLowerCase() === 'infinity') return reply(`Yahaha saya ndak bisa di tipu`)
>                  if (args[2].includes("-")) return reply(`Jangan menggunakan -`)
>                  addBalance(mentioned[0], parseInt(args[2]), balance)
>                  reply(`Sukses gift balance sebesar $${args[2]} kepada @${mentioned[0].split("@")[0]}`)
>             }
>             break
> ```

Thankss

**Comment by imamadi19** [comment]
> > > > 
> > > 
> > > 
> > > perasaan ga error dah, blum install ffmpeg kali
> > 
> > 
> > ![IMG_20211220_164308](https://user-images.githubusercontent.com/84767049/146746682-c74f8e0d-1156-4bca-95d4-cdb97d55c08a.jpg) Sama fitur tictactoe
> 
> ajg nama gw🗿

Emng itu lu? 🗿

**Comment by akmallxx** [comment]
> > > > > 
> > > > 
> > > > 
> > > > perasaan ga error dah, blum install ffmpeg kali
> > > 
> > > 
> > > ![IMG_20211220_164308](https://user-images.githubusercontent.com/84767049/146746682-c74f8e0d-1156-4bca-95d4-cdb97d55c08a.jpg) Sama fitur tictactoe
> > 
> > 
> > ajg nama gw🗿
> 
> Emng itu lu? 🗿

ga juga

**Comment by rtwone** [comment]
> > > 
> > 
> > perasaan ga error dah, blum install ffmpeg kali
> 
> ![IMG_20211220_164308](https://user-images.githubusercontent.com/84767049/146746682-c74f8e0d-1156-4bca-95d4-cdb97d55c08a.jpg)
> Sama fitur tictactoe

pasti package lu ganti
